### ISSUE TITLE
Uncaught Error: Cannot find module 'JQuery'

### ISSUE THREAD

**Issue by samuelnovaes** [github-vipera/dynamicengine-tools#2]
![captura de tela_2017-04-09_18-56-59](https://cloud.githubusercontent.com/assets/16156987/24841247/6ce2c6b0-1d56-11e7-81bc-a135aa802cd4.png)

**Comment by github-vipera** [comment]
Fixed

**Comment by github-vipera** [comment]
@samuelnovaes , Thank you for your help.
